(in-package :cl-user)
(named-readtables:in-readtable rutilsx:rutilsx-readtable)

(defclass ap-nertagger1 (ap-nertagger)
  ()
  (:documentation
   ""))

(defmethod extract-fs ((model ap-nertagger1) &rest args)
  (macrolet ((word-props (i word)
               `(when (and ,word (not (blankp ,word)))
                  (make-fs (,(strcat i " word-has-numbers")
                            (some 'digit-char-p ,word))
                           (,(strcat i " word-upcase")
                            (every 'upper-case-p ,word))
                           (,(strcat i " word-capcase")
                            (upper-case-p (? ,word 0)))
                           (,(strcat i " word-camcase")
                            (and (some 'upper-case-p ,word)
                                 (some 'lower-case-p ,word)))
                           (,(strcat i " word-international")
                            (some 'latin-char-p ,word))))))
    (with (((i ctx) args)
           (sent (? ctx :sent))
           ((prev2 prev cur next next2) (mapcar ^(? sent i)
                                                (range (- i 2) (+ i 3)))))
      (cons @cur.word
            (append (make-fs ;"bias"
                     ("i sent-beg" (= i 2))
                     ("i sent-end" (= i (- (length sent) 3)))
                     ("i len" (length @cur.word))
                     ("i word" @cur.word)
                     ("i-1 word" @prev.word)
                     ("i-2 word" @prev2.word)
                     ("i+1 word" @next.word)
                     ("i+2 word" @next2.word)
                     ("i-1 ner" (? ctx :prev))
                     ("i-2 ner" (? ctx :prev2))
                     ("i-1 ner + i-2 ner" (? ctx :prev) (? ctx :prev2))
                     ("i-1 ner + i word" (? ctx :prev) @cur.word)
                     ("quoted" (? ctx :quoted)))
                    (word-props "i" @cur.word)
                    (word-props "i-1" @prev.word)
                    (word-props "i+1" @next.word))))))
